### PR TITLE
Add functionality for using predefined filters in incident filter toolbar

### LINKED ISSUE #173: Have a drop down menu on the front page to select an existing filter
There will potentially be a lot of alerts in Argus. A nice way to limit the number of alarms is by filters. But currently filters are only possible to tie up with notification profiles. 

Is it possible to make filters visible on the front page and maybe also make me choose a default filter on my user so that this filter is active as soon as I log in to Argus?

### PR DESCRIPTION
**Pull request by jorgenbele**
Closes #173

### CODE REVIEW

**Comment by lunkwill42** [comment]
Not sure whether it's related to this specific PR, but I keep getting these errors in the frontend when testing this:
```
TypeError: this.connect is not a function
checkConnection
src/services/RealtimeService.ts:42

  39 |   console.log("checking connection");
  40 |   if (!this.ws || this.ws.readyState == WebSocket.CLOSED) {
  41 |     this.state = "closed";
> 42 |     this.connect();
     | ^  43 |   }
  44 | }
  45 | 
```

**Comment by jorgenbele** [comment]
@lunkwill42 That in not an error related to this PR. It's instead related to websockets not working correctly

**Review by hmpf — CHANGES_REQUESTED** [review]
It looks like the file **classnames.tsx** has not been commited (or maybe you moved it?) Please add it, and please also rebase on master. 

```
/home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx
TypeScript error in /home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx(6,24):
Could not find a declaration file for module 'classnames'. '/home/hm/GIT/campus/Argus-frontend/node_modules/classnames/index.js' implicitly has an 'any' type.
  Try `npm install @types/classnames` if it exists or add a new declaration (.d.ts) file containing `declare module 'classnames';`  TS7016

    4 | import Button, { ButtonProps } from "@material-ui/core/Button";
    5 |
  > 6 | import classNames from "classnames";
      |                        ^
    7 |
    8 | const useStyles = makeStyles((theme: Theme) =>
    9 |   createStyles({
```

**Comment by jorgenbele** [comment]
> It looks like the file **classnames.tsx** has not been commited (or maybe you moved it?) Please add it, and please also rebase on master.
> 
> ```
> /home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx
> TypeScript error in /home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx(6,24):
> Could not find a declaration file for module 'classnames'. '/home/hm/GIT/campus/Argus-frontend/node_modules/classnames/index.js' implicitly has an 'any' type.
>   Try `npm install @types/classnames` if it exists or add a new declaration (.d.ts) file containing `declare module 'classnames';`  TS7016
> 
>     4 | import Button, { ButtonProps } from "@material-ui/core/Button";
>     5 |
>   > 6 | import classNames from "classnames";
>       |                        ^
>     7 |
>     8 | const useStyles = makeStyles((theme: Theme) =>
>     9 |   createStyles({
> ```

You are missing the new typing package for `classnames`. Local files are imported by relative path in this project (would've been "./classnames"), but `classnames` is a package. Install it by running `npm install`.

**Comment by hmpf** [comment]
> > It looks like the file **classnames.tsx** has not been commited (or maybe you moved it?) Please add it, and please also rebase on master.
> > ```
> > /home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx
> > TypeScript error in /home/hm/GIT/campus/Argus-frontend/src/components/buttons/OutlinedButton.tsx(6,24):
> > Could not find a declaration file for module 'classnames'. '/home/hm/GIT/campus/Argus-frontend/node_modules/classnames/index.js' implicitly has an 'any' type.
> >   Try `npm install @types/classnames` if it exists or add a new declaration (.d.ts) file containing `declare module 'classnames';`  TS7016
> > /../
> > ```
> 
> You are missing the new typing package for `classnames`. Local files are imported by relative path in this project (would've been "./classnames"), but `classnames` is a package. Install it by running `npm install`.

We need a better way of flagging the need for rerunning `npm install`. I think a new label is best as it is more shouty (and quicker to add) than remembering to to mention running `npm install` in the PR/issue itself, or noticing what the error message says :)

**Comment by hmpf** [comment]
I guess we can reuse the "dependencies"-tag, I'll try to make it more ugly and loud.

**Comment by hmpf** [comment]
> @lunkwill42 That in not an error related to this PR. It's instead related to websockets not working correctly

I've merged the fix for that.

**Comment by jorgenbele** [comment]
@hmpf well it doesn't apply to this PR, it applies to a PR that was merged a month ago. I think testing should be done cleanly anyways. I do think it should be tagged though, and in a separate commit  - great suggestion

**Review by hmpf — APPROVED** [review]
Manually tested, works.

This new feature really drives home the need for being able to save preferred status (open/closed) and ackedness (yes/no) in a filter!

**Pull request merged**
