### PR TITLE
Feat network problem indicator

### PR DESCRIPTION
**Pull request by jorgenbele**

### CODE REVIEW

**Comment by jorgenbele** [comment]
Closes #237

**Comment by jorgenbele** [comment]
Here is what it looks like when the network connection to the backend is detected: 
image

**Review by lunkwill42 — COMMENTED** [review]
Tested superficially, and it looks :+1: 😄 

However, in dev mode the error keeps popping up as a huge exception I need to dismiss before I can see the friendly error message from Argus-frontend. 

Assuming this behavior is intentional, and will not bother regular users?

I'll leave the final decision up to @hmpf :)

**Comment by jorgenbele** [comment]
> Tested superficially, and it looks +1 smile
> 
> However, in dev mode the error keeps popping up as a huge exception I need to dismiss before I can see the friendly error message from Argus-frontend.
> 
> Assuming this behavior is intentional, and will not bother regular users?
> 
> I'll leave the final decision up to @hmpf :)

Yes, the exception popup in debug mode is expected, and happens whenever any unhandled exception is thrown AFAIK. I don't think there is any way to remove this without negative side-effects. You could probably modify your local development environment, but in testing these error messages are useful.

**Review by hmpf — APPROVED** [review]

**Pull request merged**
