### PR TITLE
Make interval update more user friendly

### LINKED ISSUE #323: Make interval updates more user friendly
### Problem
With Argus in Interval mode updating, the list of incidents refreshes in a way that is annoying for the user. 
This happens even if there is no changes made to the list of incidents that is currently viewed.
The refresh hinders work as certain actions cannot be done while this is happening, such as selecting incidents.
The visual noise is also annoying, as the refresh happens quite often.

### Possible solution
Only update the view if there is a change relevant to the current filter (new incidents or changes to existing incidents)

### PR DESCRIPTION
**Pull request by podliashanyk**
Interval update is postponed if user opens incident detail view, or has at least one incident checked.

Closes #323

### CODE REVIEW

**Review by lunkwill42 — COMMENTED** [review]
This does appear to work as advertised, and I support the initiative :)

Again, not sure I'm able to make an effective code review, but I have a couple
of questions:

1. This seems, in effect, to restart the refresh timer once the user "stops
   interacting" with the incident list.  I.e., if the user opens the incident
   dialog box, looks around and closes it again, 5 minutes could have passed
   with no refreshes - still, it will now take 30 seconds until the next
   refresh.
   
   Is this assumption correct? If so - should this be considered the correct
   behavior?
   

2. When I click on an open incident, the console now logs a long error at me. I
   not equipped to decide whether this problem was already present, or whether
   it was introduced by this PR:

   ```
   Warning: Each child in a list should have a unique "key" prop.

   Check the render method of `IncidentDetails`. See https://fb.me/react-warning-keys for more information.
       in WithStyles(ForwardRef(Grid)) (at IncidentDetails.tsx:527)
       in IncidentDetails (at IncidentTable.tsx:539)
       in div (created by ForwardRef(DialogContent))
       in ForwardRef(DialogContent) (created by WithStyles(ForwardRef(DialogContent)))
       in WithStyles(ForwardRef(DialogContent)) (created by WithStyles(WithStyles(ForwardRef(DialogContent))))
       in WithStyles(WithStyles(ForwardRef(DialogContent))) (at Modal.tsx:117)
       in div (created by ForwardRef(Paper))
       in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
       in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Dialog))
       in div (created by Transition)
       in Transition (created by ForwardRef(Fade))
       in ForwardRef(Fade) (created by Unstable_TrapFocus)
       in Unstable_TrapFocus (created by ForwardRef(Modal))
       in div (created by ForwardRef(Modal))
       in ForwardRef(Portal) (created by ForwardRef(Modal))
       in ForwardRef(Modal) (created by ForwardRef(Dialog))
       in ForwardRef(Dialog) (created by WithStyles(ForwardRef(Dialog)))
       in WithStyles(ForwardRef(Dialog)) (at Modal.tsx:106)
       in Modal (at IncidentTable.tsx:547)
       in div (at IncidentTable.tsx:546)
       in ClickAwayListener (at IncidentTable.tsx:545)
       in MinimalIncidentTable (at FilteredIncidentTable.tsx:268)
       in FilteredIncidentsProvider (at FilteredIncidentTable.tsx:267)
       in div (at FilteredIncidentTable.tsx:266)
       in FilteredIncidentTable (at IncidentView.tsx:24)
       in IncidentComponent (at IncidentView.tsx:70)
       in IncidentsProvider (at IncidentView.tsx:68)
       in SelectedFilterProvider (at IncidentView.tsx:67)
       in div (at IncidentView.tsx:63)
       in IncidentView (created by Context.Consumer)
       in withRouter(IncidentView) (at App.tsx:36)
       in Unknown (at protected.route.tsx:53)
       in Route (at protected.route.tsx:48)
       in ProtectedRoute (at App.tsx:48)
       in Switch (at App.tsx:47)
       in ApiInterceptor (at App.tsx:46)
       in AlertSnackbarProvider (at App.tsx:45)
       in ThemeProvider (at App.tsx:44)
       in div (at App.tsx:43)
       in App (at src/index.tsx:15)
       in AppProvider (at src/index.tsx:14)
       in StoreProvider (at src/index.tsx:13)
       in Router (created by BrowserRouter)
       in BrowserRouter (at src/index.tsx:12) index.js:1
   ```

**Comment by podliashanyk** [comment]
> 1. This seems, in effect, to restart the refresh timer once the user "stops interacting" with the incident list.  I.e., if the user opens the incident dialog box, looks around and closes it again, 5 minutes could have passed with no refreshes - still, it will now take 30 seconds until the next refresh.
>    Is this assumption correct? If so - should this be considered the correct behavior?

That is a correct assumption. I guess restarting the timer is less user friendly, so I will look at it. :)

> 2. When I click on an open incident, the console now logs a long error at me (the dialog box appears as it should, though, so everything looks normal from the user's perspective). I'm not equipped to decide whether this problem was already present, or whether it was introduced by this PR

This warning was there before PR. 😅

**Comment by podliashanyk** [comment]
## Changes made:

- Removes blinking on incidents updates. All updates in the interval mode work the same way as in the realtime mode, meaning that the external modifications of incidents, update internal data in a targeted fashion, and without blinking.
- Updates ticket-url input field if url was modified externally (by some other user) in both interval and realtime mode.

**Review by hmpf — APPROVED** [review]

**Review by lunkwill42 — APPROVED** [review]
Works like a charm!  :-)

**Pull request merged**
