### PR TITLE
Document release workflow

### LINKED ISSUE #216: Adopt a versioning scheme for Argus-frontend
As of today, there is no versioning scheme in Argus-frontend.
Since its development is independent from the backend, it should have its own versioning.

Having a versioning scheme helps with development, managing milestones, and is a requirement for user issue tracking (see #215).

I suggest evaluating this with regard to the current dev's preferences.
Semantic versioning (https://semver.org/) seems to be a good and widely used/supported standard, among others.

### PR DESCRIPTION
**Pull request by podliashanyk**
### Changes made:

- [x] Added semantic-release dependency (for auto generated changelogs, SemVer bumps)

- [x] Created release.config 
    - [x] Changes on master branch trigger CHANGELOGs generation and version bump
- [x] Define how coarse-grained CHANGELOGS and version bumps should be
    - [x] In CONTRIBUTING.md: describe this projects commit message convention so that CHANGELOGs generation and version bumps will be executed at a defined (coarse-grained) level. Will be based on https://www.conventionalcommits.org/en/v1.0.0/
- [x] Add release task to .yml

### Things to consider:

- [ ] Create a separate release branch, since version bumps based on master updates would be too frequent

Please, comment on any other ideas, solutions, restrictions.

Closes #216

### CODE REVIEW

**Comment by hmpf** [comment]
I am a big, big, HUGE fan of [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/). Each of the fifty characters of the shortlog (first line of a commit message) are very precious to me, I do not want to spend any on a prefix. Writing good shortlogs is hard. (I make a sole exception for Django: "Migrate:" whenever there is an automated SQL schema migration that actually touches the database schema, which isn't all of them.)  I don't put issue numbers in the shortlog either, and I've worked hard to internalize the template "_This will_ **your commit shortlog here**".

Having read [https://www.conventionalcommits.org/en/v1.0.0/](https://www.conventionalcommits.org/en/v1.0.0/), I'm not a fan.

If you look at the earliest commits, they used an emoji-based prefix-system, which does save on characters, but also made some of my favorite tools core dump.

**Comment by hmpf** [comment]
Googling the subject I found [Effortlessly maintain a high quality change log with Git notes ](https://dev.to/leehambley/effortlessly-maintain-a-high-quality-change-log-with-git-notes-4bm5) which I think I will test on some smaller projects. Though, that might solve/improve the release notes/changelog problem, not how to set a new version number problem.

**Review by hmpf — COMMENTED** [review]
See conversation.

**Comment by podliashanyk** [comment]
> I am a big, big, HUGE fan of [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/). Each of the fifty characters of the shortlog (first line of a commit message) are very precious to me, I do not want to spend any on a prefix. Writing good shortlogs is hard. (I make a sole exception for Django: "Migrate:" whenever there is an automated SQL schema migration that actually touches the database schema, which isn't all of them.) I don't put issue numbers in the shortlog either, and I've worked hard to internalize the template "_This will_ **your commit shortlog here**".
> 
> Having read https://www.conventionalcommits.org/en/v1.0.0/, I'm not a fan.
> 
> If you look at the earliest commits, they used an emoji-based prefix-system, which does save on characters, but also made some of my favorite tools core dump.

I did not find any alternative to automated or (semi-automated) npm versioning, that does not rely on conventional commits. 
But if it is important that versioning becomes automated, what about following conventional commits only on (relevant) PR merges? 
By this I mean that merge commit name will change from:

Screenshot 2021-08-05 at 17 21 17

 to:

Screenshot 2021-08-05 at 17 22 14

This solution:

- [ ] requires a separate release branch
- [ ] requires that merge-commit messages of PRs, relevant for version bump description, should follow conventional commits. Any other commits, or merge-commit messages of PRs that are irrelevant for version bump description (too fine-grained), may follow [any other preferred convention](https://chris.beams.io/posts/git-commit/)
- [ ] does not conflict with [changelogs solution that you mentioned](https://dev.to/leehambley/effortlessly-maintain-a-high-quality-change-log-with-git-notes-4bm5), both can be implemented independently 

Does it sound like a viable solution?

**Comment by hmpf** [comment]
We had a (physical!) meeting and decided not to automate changing version numbers.

What needs documenting (should go in CONTRIBUTING I guess) is that the version in `package.json` should be in sync with a git tag. The version in `package.json` is a semver string that starts with an integer, and the tag is identical. The tag needs to be annotated, that is: have a very short summary.

**Pull request closed without merging**
