### PR TITLE
Feat ui upgrade

### LINKED ISSUE #148: Provide canonical URLs to access the incident details "dialog"
It should be possible for 3rd party tools, like ticketing systems, to link back to the Argus details page for a single Incident, which means that each incident needs a canonical URL to enable access to this.

Since the Argus UI is a single-page-application, the details dialog/modal is currently only available by manually clicking through the interface.

### PR DESCRIPTION
**Pull request by jorgenbele**
Closes #148

### CODE REVIEW

**Review by hmpf — COMMENTED** [review]
Could you attempt to extract the subset of patches that will fix #167? So we can get that out of the door.

**Comment by hmpf** [comment]
It looks like you've started the stuff necessary to solve #148. Could you add the numbers to any other issue this will solve to this issue so we can close them when solved?

**Comment by hmpf** [comment]
Could you rebase on v1.0.0 in order to get rid of what's already merged? It's very hard to review as is.

**Comment by jorgenbele** [comment]
> It looks like you've started the stuff necessary to solve #148. Could you add the numbers to any other issue this will solve to this issue so we can close them when solved?

I haven't really made any progress on this AFAIK, but I will try to get it done now.

> Could you rebase on v1.0.0 in order to get rid of what's already merged? It's very hard to review as is.

Working on it.

**Comment by jorgenbele** [comment]
This is now outdated, closing.

**Pull request closed without merging**
