### PR TITLE
Allow customizable timestamps

### PR DESCRIPTION
**Pull request by jorgenbele**
This implements functionality of #220 as well as:
1. Removing use of moment.js (deprecated/no longer maintained), replacing it with date-fns
2. Adding ability to specify format in configuration file, and also conditionally enable seconds/timezone-offset by passing an options dict to `formatTimestamp()`

### CODE REVIEW

**Comment by jorgenbele** [comment]
Closes #137

**Comment by jorgenbele** [comment]
Closes #220

**Review by lunkwill42 — CHANGES_REQUESTED** [review]
This looks lovely on the incident list! :+1:

My only feedback is that I would actually prefer including seconds in the timestamp when viewing the event details dialog (after all, details should be detailed!) :-)

**Comment by jorgenbele** [comment]
> This looks lovely on the incident list! +1
> 
> My only feedback is that I would actually prefer including seconds in the timestamp when viewing the event details dialog (after all, details should be detailed!) :-)

I've set the `withSeconds` flag for all uses in the IncidentDetails. Does that work?

**Review by hmpf — APPROVED** [review]

**Comment by hmpf** [comment]
> > This looks lovely on the incident list! +1
> > My only feedback is that I would actually prefer including seconds in the timestamp when viewing the event details dialog (after all, details should be detailed!) :-)
> 
> I've set the `withSeconds` flag for all uses in the IncidentDetails. Does that work?

Yep, and I can verify: it looks good, so I'm merging.

**Pull request merged**
